name: Build & Update everdues root

on:
  push:
    branches:
      - 'ci/cd'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/everdues/everdues-deployer:latest
      credentials:
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run an upgrade of the Everdues root
      run: |
        cd everdues/scripts && bash upgrade-all.sh dev